import { default as EsriBasemap, BasemapProperties as EsriBasemapProperties } from '@arcgis/core/Basemap';
import { default as EsriColour } from '@arcgis/core/Color';
import { default as EsriConfig } from '@arcgis/core/config';
import { ArcadeExecutor as EsriArcadeExecutor, Profile as EsriProfile } from '@arcgis/core/arcade';
import { default as EsriCollection } from '@arcgis/core/core/Collection';
import { ResourceHandle as EsriResourceHandle } from '@arcgis/core/core/Handles';
import { watch as EsriWatch } from '@arcgis/core/core/reactiveUtils';
import { ScreenPoint as EsriScreenPoint } from '@arcgis/core/core/types';
import { GeometryUnion as EsriGeometry } from '@arcgis/core/geometry/types';
import { default as EsriGraphic } from '@arcgis/core/Graphic';
import { default as EsriExtent } from '@arcgis/core/geometry/Extent';
import { default as EsriMultipoint } from '@arcgis/core/geometry/Multipoint';
import { default as EsriPoint } from '@arcgis/core/geometry/Point';
import { default as EsriPolygon } from '@arcgis/core/geometry/Polygon';
import { default as EsriPolyline } from '@arcgis/core/geometry/Polyline';
import { default as EsriSpatialReference } from '@arcgis/core/geometry/SpatialReference';
import { fromJSON as EsriGeometryFromJson } from '@arcgis/core/geometry/support/jsonUtils';
import { default as EsriFeatureLayer, FeatureLayerProperties as EsriFeatureLayerProperties } from '@arcgis/core/layers/FeatureLayer';
import { default as EsriGraphicsLayer, GraphicsLayerProperties as EsriGraphicsLayerProperties } from '@arcgis/core/layers/GraphicsLayer';
import { default as EsriImageryLayer, ImageryLayerProperties as EsriImageryLayerProperties } from '@arcgis/core/layers/ImageryLayer';
import { default as EsriImageryTileLayer, ImageryTileLayerProperties as EsriImageryTileLayerProperties } from '@arcgis/core/layers/ImageryTileLayer';
import { default as EsriLayer, LayerLayerviewCreateEvent as EsriLayerLayerviewCreateEvent } from '@arcgis/core/layers/Layer';
import { default as EsriMapImageLayer, MapImageLayerProperties as EsriMapImageLayerProperties } from '@arcgis/core/layers/MapImageLayer';
import { default as EsriOpenStreetMapLayer, OpenStreetMapLayerProperties as EsriOpenStreetMapLayerProperties } from '@arcgis/core/layers/OpenStreetMapLayer';
import { default as EsriTileLayer, TileLayerProperties as EsriTileLayerProperties } from '@arcgis/core/layers/TileLayer';
import { default as EsriWMSLayer, WMSLayerProperties as EsriWMSLayerProperties } from '@arcgis/core/layers/WMSLayer';
import { default as EsriVectorTileLayer, VectorTileLayerProperties as EsriVectorTileLayerProperties } from '@arcgis/core/layers/VectorTileLayer';
import { default as EsriFeatureFilter, FeatureFilterProperties as EsriFeatureFilterProperties } from '@arcgis/core/layers/support/FeatureFilter';
import { default as EsriFeatureReductionCluster } from '@arcgis/core/layers/support/FeatureReductionCluster';
import { default as EsriField, FieldProperties as EsriFieldProperties } from '@arcgis/core/layers/support/Field';
import { default as EsriLOD } from '@arcgis/core/layers/support/LOD';
import { default as EsriSublayer } from '@arcgis/core/layers/support/Sublayer';
import { default as EsriWMSSublayer } from '@arcgis/core/layers/support/WMSSublayer';
import { default as EsriMap, MapProperties as EsriMapProperties } from '@arcgis/core/Map';
import { default as EsriClassBreaksRenderer } from '@arcgis/core/renderers/ClassBreaksRenderer';
import { default as EsriSimpleRenderer } from '@arcgis/core/renderers/SimpleRenderer';
import { default as EsriUniqueValueRenderer } from '@arcgis/core/renderers/UniqueValueRenderer';
import { default as EsriClassBreakInfo } from '@arcgis/core/renderers/support/ClassBreakInfo';
import { default as EsriUniqueValueInfo } from '@arcgis/core/renderers/support/UniqueValueInfo';
import { default as EsriRequest } from '@arcgis/core/request';
import { RequestOptions as EsriRequestOptions, RequestResponse as EsriRequestResponse } from '@arcgis/core/request/types';
import { RendererUnion as EsriRenderer } from '@arcgis/core/renderers/types';
import { default as EsriQuery } from '@arcgis/core/rest/support/Query';
import { default as EsriPictureMarkerSymbol } from '@arcgis/core/symbols/PictureMarkerSymbol';
import { default as EsriSimpleFillSymbol } from '@arcgis/core/symbols/SimpleFillSymbol';
import { default as EsriSimpleLineSymbol } from '@arcgis/core/symbols/SimpleLineSymbol';
import { default as EsriSimpleMarkerSymbol } from '@arcgis/core/symbols/SimpleMarkerSymbol';
import { Symbol2DUnion as EsriSymbol } from '@arcgis/core/symbols/types';
import { fromJSON as EsriSymbolFromJson } from '@arcgis/core/symbols/support/jsonUtils';
import { default as EsriFeatureLayerView } from '@arcgis/core/views/layers/FeatureLayerView';
import { default as EsriGraphicsLayerView } from '@arcgis/core/views/layers/GraphicsLayerView';
import { default as EsriLayerView } from '@arcgis/core/views/layers/LayerView';
import { default as EsriMapView, MapViewProperties as EsriMapViewProperties } from '@arcgis/core/views/MapView';
import { GoToOptions2D as EsriGoToOptions2D, GraphicHit as EsriGraphicHit, UserSettings as EsriUserSettings } from '@arcgis/core/views/types';
import { ClickEvent as EsriViewClickEvent, DoubleClickEvent as EsriViewDoubleClickEvent, DragEvent as EsriViewDragEvent, PointerEventCommon as EsriViewPointerEventCommon, PointerMoveEvent as EsriViewPointerMoveEvent } from '@arcgis/core/views/input/types';
import { default as EsriColorBackground, ColorBackgroundProperties as EsriColorBackgroundProperties } from '@arcgis/core/webmap/background/ColorBackground';
import { CreateEvent as EsriSketchCreateEvent, UpdateEvent as EsriSketchUpdateEvent } from '@arcgis/core/widgets/Sketch/types';
declare class EsriAPI {
    static Basemap(prams: EsriBasemapProperties): Promise<EsriBasemap>;
    static Map(prams: EsriMapProperties): Promise<EsriMap>;
    static MapView(prams: EsriMapViewProperties): Promise<EsriMapView>;
    static FeatureLayer(prams: EsriFeatureLayerProperties): Promise<EsriFeatureLayer>;
    static GraphicsLayer(prams: EsriGraphicsLayerProperties): Promise<EsriGraphicsLayer>;
    static ImageryLayer(prams: EsriImageryLayerProperties): Promise<EsriImageryLayer>;
    static ImageryTileLayer(prams: EsriImageryTileLayerProperties): Promise<EsriImageryTileLayer>;
    static MapImageLayer(prams: EsriMapImageLayerProperties): Promise<EsriMapImageLayer>;
    static OpenStreetMapLayer(prams: EsriOpenStreetMapLayerProperties): Promise<EsriOpenStreetMapLayer>;
    static TileLayer(prams: EsriTileLayerProperties): Promise<EsriTileLayer>;
    static VectorTileLayer(prams: EsriVectorTileLayerProperties): Promise<EsriVectorTileLayer>;
    static WMSLayer(prams: EsriWMSLayerProperties): Promise<EsriWMSLayer>;
    static ArcadeExecutor(script: string, profile: EsriProfile): Promise<EsriArcadeExecutor>;
    static ColorBackground(prams: EsriColorBackgroundProperties): Promise<EsriColorBackground>;
    static FeatureFilter(prams: EsriFeatureFilterProperties): Promise<EsriFeatureFilter>;
    static FieldFromJson(json: any): Promise<EsriField>;
    static Query(): Promise<EsriQuery>;
    static QueryByIds(url: string, query: EsriQuery, options?: EsriRequestOptions): Promise<Array<number>>;
    static RendererFromJson(json: any): Promise<EsriRenderer>;
}
export { EsriAPI, type EsriArcadeExecutor, type EsriBasemap, type EsriClassBreakInfo, type EsriClassBreaksRenderer, type EsriCollection, EsriColour, type EsriColorBackground, EsriConfig, EsriExtent, type EsriFeatureFilter, type EsriFeatureLayer, type EsriFeatureLayerProperties, type EsriFeatureLayerView, type EsriFeatureReductionCluster, type EsriField, type EsriFieldProperties, type EsriGeometry, EsriGeometryFromJson, type EsriGoToOptions2D, EsriGraphic, type EsriGraphicHit, type EsriGraphicsLayer, type EsriGraphicsLayerProperties, type EsriGraphicsLayerView, type EsriImageryLayer, type EsriImageryLayerProperties, type EsriImageryTileLayer, type EsriImageryTileLayerProperties, type EsriLayer, type EsriLayerLayerviewCreateEvent, type EsriLayerView, type EsriLOD, type EsriMap, type EsriMapImageLayer, type EsriMapImageLayerProperties, type EsriMapProperties, type EsriMapView, EsriMultipoint, type EsriOpenStreetMapLayer, type EsriOpenStreetMapLayerProperties, EsriPictureMarkerSymbol, EsriPoint, EsriPolygon, EsriPolyline, type EsriProfile, type EsriQuery, type EsriRenderer, EsriRequest, type EsriRequestOptions, type EsriRequestResponse, type EsriResourceHandle, type EsriScreenPoint, EsriSimpleFillSymbol, EsriSimpleLineSymbol, EsriSimpleMarkerSymbol, type EsriSimpleRenderer, type EsriSketchCreateEvent, type EsriSketchUpdateEvent, EsriSpatialReference, type EsriSublayer, type EsriSymbol, EsriSymbolFromJson, type EsriTileLayer, type EsriTileLayerProperties, type EsriUniqueValueInfo, type EsriUniqueValueRenderer, type EsriUserSettings, type EsriVectorTileLayer, type EsriVectorTileLayerProperties, type EsriViewClickEvent, type EsriViewDoubleClickEvent, type EsriViewDragEvent, type EsriViewPointerEventCommon, type EsriViewPointerMoveEvent, EsriWatch, type EsriWMSLayer, type EsriWMSLayerProperties, type EsriWMSSublayer };
