name: PR Commenter

on:
    pull_request_target:
        types: [opened]

permissions:
    issues: write
    pull-requests: write

jobs:
    comment-on-pr:
        runs-on: ubuntu-latest
        steps:
            - name: Comment on the PR
              uses: peter-evans/create-or-update-comment@v5
              env:
                  PR_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
                  PR_HEAD_REF: ${{ github.head_ref }}
              with:
                  token: ${{ github.token }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      Your demo site is ready! 🚀

                      Enhanced Testing:
                      Samples: https://${PR_OWNER}.github.io/ramp4-pcar4/${PR_HEAD_REF}/demos/enhanced-samples.html
                      Catalogue: https://${PR_OWNER}.github.io/ramp4-pcar4/${PR_HEAD_REF}/demos/enhanced-all.html

                      Legacy Testing:
                      Main: https://${PR_OWNER}.github.io/ramp4-pcar4/${PR_HEAD_REF}/
                      Catalogue: https://${PR_OWNER}.github.io/ramp4-pcar4/${PR_HEAD_REF}/demos/index-all.html
                      Samples: https://${PR_OWNER}.github.io/ramp4-pcar4/${PR_HEAD_REF}/demos/index-samples.html

                      ![](https://byob.yarr.is/ramp4-pcar4/ramp4-pcar4/tsbadge-pr-${{ github.event.pull_request.number }}) ![](https://byob.yarr.is/ramp4-pcar4/ramp4-pcar4/lintbadge-pr-${{ github.event.pull_request.number }})
