name: Publish to GitHub pages

on:
    workflow_call:

jobs:
    deploy-to-pages:
        name: Deploy to GitHub pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Get dist files
              uses: actions/cache@v3
              with:
                  path: dist
                  key: dist-${{ github.sha }}

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  branch: gh-pages
                  folder: dist
                  target-folder: ${{ github.ref_name }}

            - uses: actions/github-script@v6
              name: Post link to demo for PR's
              if: github.event_name == 'pull_request' && github.event.action == 'opened'
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `Your demo site is ready! 🚀 Visit it here: https://${{github.event.pull_request.head.user.login}}.github.io/ramp4-pcar4/${{github.head_ref}}/`
                      })
